daemon off;
worker_processes  2;
events {
  worker_connections 	1024;
}
http {
  server {
    listen  9876;
    server_name 0.0.0.0;

    # for frontend
    location / {
        proxy_pass http://solomon-web:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # for backend
    location /solomon-api/ {
        proxy_pass http://solomon-api:8888/;
        # 헤더 관련 설정 추가
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # WebSocket 지원을 위한 설정
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # 타임아웃 설정
        proxy_connect_timeout 180s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;
    }
  }
  server_tokens off;
}